wicket:
  stuff:
    datastore:
      hazelcast:
        enabled: false
  core:
    resourcesettings:
      packageresourceguard:
        pattern:
        - +*.map
    csrf:
      accepted-origins:
        - localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  compression:
    enabled: true
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    show-sql: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-h2.sql
  datasource:
      url: ${databaseUrl:jdbc:postgresql://localhost:5433/postgres}
# Keep for kubernets? :  url: ${databaseUrl:jdbc:postgresql://localhost:5432/dibser/masterdb?ssl=true&sslmode=require}
      username: ${databaseUsername:postgres}
      password: ${databasePassword:postgress}
  liquibase:
    enabled: false
